// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyYjsUpdateReducer from "../apply_yjs_update_reducer";
import DocumentCreateReducer from "../document_create_reducer";
import DocumentUpdateTitleReducer from "../document_update_title_reducer";
import UpdateAwarenessReducer from "../update_awareness_reducer";

export type ApplyYjsUpdateParams = __Infer<typeof ApplyYjsUpdateReducer>;
export type DocumentCreateParams = __Infer<typeof DocumentCreateReducer>;
export type DocumentUpdateTitleParams = __Infer<typeof DocumentUpdateTitleReducer>;
export type UpdateAwarenessParams = __Infer<typeof UpdateAwarenessReducer>;

