// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AwarenessState = __t.object("AwarenessState", {
  userId: __t.u64(),
  docId: __t.string(),
  stateJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AwarenessState = __Infer<typeof AwarenessState>;

export const Document = __t.object("Document", {
  id: __t.string(),
  title: __t.string(),
  ownerId: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Document = __Infer<typeof Document>;

export const YjsUpdate = __t.object("YjsUpdate", {
  id: __t.u64(),
  docId: __t.string(),
  updateBytes: __t.byteArray(),
  clientId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type YjsUpdate = __Infer<typeof YjsUpdate>;

